title: MCE Controller
logo: https://tig.github.io/mcec/Guillen256x256.png
show_downloads: true
theme: jekyll-theme-dinky
google_analytics: UA-4945529-6
github:
  install_url: https://github.com/tig/mcec/releases
